### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by albinekb** [nordnet/cordova-hot-code-push-local-dev-addon#1]
When i add this plugin, i can't build for ios anymore.

Log: http://pastebin.com/AuYY3UZT

Xcode version 6.4

**Comment by nikDemyankov** [comment]
This plugin uses Socket.IO library, and it requires Xcode 7. So, if you want to use local development mode - then you need Xcode 7.

For Hot Code Push plugin without local development add-on you can use Xcode 6.4.

**Comment by albinekb** [comment]
Cool, updated now and it works!
Sorry, missed that in the readme.

**Comment by nikDemyankov** [comment]
Great :)

**Comment by albinekb** [comment]
@nikDemyankov maybe add a note saying that you need Xcode 7+ for the dev plugin in the readme for https://github.com/nordnet/cordova-hot-code-push

**Comment by nikDemyankov** [comment]
Yes, you are probably right. Thanks for the idea, will do.
