### ISSUE TITLE
Could not use link mode of cordova plugin.

### ISSUE THREAD

**Issue by robario** [nordnet/cordova-hot-code-push-local-dev-addon#10]
When using symlink to install this plugin

```
$ cordova plugin add --link ./node_modules/cordova-hot-code-push-local-dev-addon
```

It modify `./node_modules/cordova-hot-code-push-local-dev-addon/src/ios/HCPLDPlugin.h`
not `./platforms/ios/*/Plugins/cordova-hot-code-push-local-dev-addon/HCPLDPlugin.h`.

In other words, this plugin modify `./plugins/cordova-hot-code-push-local-dev-addon/src/ios/HCPLDPlugin.h`.

I think a plugin should not modify itself.
It should only modify the under `./platforms/` instead.

**Comment by nikDemyankov** [comment]
It doesn't. It modifies only platform's version and not the source: https://github.com/nordnet/cordova-hot-code-push-local-dev-addon/blob/master/scripts/lib/swiftHelper.js#L181 .

So my guess that there's something wrong with symlinking.

**Comment by robario** [comment]
Certainly...
I show the difference between using link mode and not link mode.
- OS X El Capitan.
- cordova@6.2.0
- cordova-ios@4.1.1
- cordova-hot-code-push-local-dev-addon@0.2.2
- cordova-hot-code-push-plugin@1.3.2
- cordova-hot-code-push-cli@1.1.1

```
node_modules :: ./node_modules/cordova-hot-code-push-local-dev-addon/src/ios/HCPLDPlugin.h
     plugins :: ./plugins/cordova-hot-code-push-local-dev-addon/src/ios/HCPLDPlugin.h
   platforms :: ./platforms/cordova-hot-code-push-local-dev-addon/HCPLDPlugin.h
```

without link mode

```
$ cordova plugin add cordova-hot-code-push-local-dev-addon

in node_modules:1: //
in      plugins:1: //
in    platforms:1: //

$ cordova prepare ios

in node_modules:1: //
in      plugins:1: //
in    platforms:1: #import "MYPRODUCT-Swift.h"
```

with link mode

```
$ cordova plugin add --link ./node_modules/cordova-hot-code-push-local-dev-addon

in node_modules:1: //
in      plugins:1: //
in    platforms:1: //

$ cordova prepare ios

in node_modules:1: #import "MYPRODUCT-Swift.h"
in      plugins:1: #import "MYPRODUCT-Swift.h"
in    platforms:1: #import "MYPRODUCT-Swift.h"
```
