### ISSUE TITLE
Can't build iOS project with Chinese name

### ISSUE THREAD

**Issue by nikDemyankov** [nordnet/cordova-hot-code-push-local-dev-addon#11]
How to reproduce:

``` bash
cordova create china m.test.com 中国
cd china
cordova platform add ios
cordova plugin add cordova-hot-code-push-plugin
cordova plugin add cordova-hot-code-push-local-dev-addon
cordova build ios
```

The problem is that hooks can't inject Swift header into project. If we use english name for the project - it works fine.

**Comment by sckoh** [comment]
need to manually replace 
#import "_-Swift.h"
to
#import "中国-Swift.h"
in file HCPLDPlugin.h
to successfully build the project
