### ISSUE TITLE
Xcode 8 compatibility

### ISSUE THREAD

**Issue by davidellolio** [nordnet/cordova-hot-code-push-local-dev-addon#13]
Hi all,

I have installed xcode 8 beta and cordova-hot-code-push-local-dev-addon plugin have a problem of compatibility with new version SWIFT code.

How can solve this problem ? 

Thank you,
Davide

**Comment by nikDemyankov** [comment]
Hi,

I haven't tested it with Xcode 8 yet. I'll do that and get back to you. Most likely it will require just to update the swift code of the socket.io library.

**Comment by chaffeqa** [comment]
Looks like they have this issue targetted on socket.io: [on a branch](https://github.com/socketio/socket.io-client-swift/issues/437#issuecomment-243206444)

**Comment by nikDemyankov** [comment]
Yep, just need to wait for them to fix it, and then I'll update the sources.

**Comment by nikDemyankov** [comment]
Released v0.4.0. It should now build in Xcode 8.
