### ISSUE TITLE
Cant compile when other plugin is using Swift.

### ISSUE THREAD

**Issue by rollsroyc3** [nordnet/cordova-hot-code-push-local-dev-addon#15]
My project currently uses the [iOS-RTC plugin](https://github.com/eface2face/cordova-plugin-iosrtc) which is built with Swift 2.3. So far I have not been able to get both plugins to work together, have tried modifying both scripts, changing hook type, etc.. Any idea what it will take to get this to work along the other plugin?

**Comment by nikDemyankov** [comment]
I'll check it out, but it seems like there are some heavy tricks are required to build the project even with just iOS-RTC plugin. Just adding it to the clean project and trying to build fails hard.

**Comment by rollsroyc3** [comment]
I ended up forking the iOS-RTC plugin and applying a PR that updated to Swift 3.0. That seems to have taken care of it!
