### ISSUE TITLE
Use local server instead of public server

### ISSUE THREAD

**Issue by rollsroyc3** [nordnet/cordova-hot-code-push-local-dev-addon#16]
When compiling with local development enabled it seems to automatically inject the public url.

> CHCP Local Development Add-on:
    Setting config-file to local server: https://20a51a38.ngrok.com/chcp.json
    Android version code is set to 5
    iOS bundle version set to 4

Is it possible to have the config-file set to the local server instead?

**Comment by nikDemyankov** [comment]
You can check [after_prepare_hook](https://github.com/nordnet/cordova-hot-code-push-local-dev-addon/blob/master/scripts/afterPrepareHook.js). By default when you build your project - it takes server's url from `.chcpenv` file, that can be found in your project's folder.

You can probably change the url in that file. If you'll change the config and then run `cordova-hcp server` - CLI client will override it. So be careful with that.

Another thing you can try out is to use [build config](https://github.com/nordnet/cordova-hot-code-push/wiki/Build-options) of the main plugin.

Or just modify `after_prepare_hook` and point it to your server. In that case you can just change [line 14](https://github.com/nordnet/cordova-hot-code-push-local-dev-addon/blob/master/scripts/afterPrepareHook.js#L14) to your version of the config.

**Comment by rollsroyc3** [comment]
Thanks, I will look into this!

**Comment by zk922** [comment]
I have the same needs in local development. It is too slow to use the ngrok.io proxy in my country...
Changing the` .chcpenv` file after running  `cordova-hcp server` could work.But could the plugin be more configurable?
