### ISSUE TITLE
Can build/run with the plugin installed

### ISSUE THREAD

**Issue by guv3n** [nordnet/cordova-hot-code-push-local-dev-addon#19]
Hi

First I'd like to say thank you again for this plugin, I've been using it with cordova-hot-code-push for more than 1 year and it's great.

Today I have a problem with this plugin. I can't build anymore. It seems related to the plugin since build is working when I remove the local-dev-addon

Here is the end of my build log, I can provide you with more if needed. 

** BUILD FAILED **

The following build commands failed:
        CompileSwift normal x86_64 /Users/Guven/Work/clm-cordova/platforms/ios/YDNCRM/Plugins/cordova-hot-code-push-local-dev-addon/SocketIOClientSwift/SocketEngine.swift
        CompileSwift normal x86_64 /Users/Guven/Work/clm-cordova/platforms/ios/YDNCRM/Plugins/cordova-hot-code-push-local-dev-addon/SocketIOClientSwift/SocketIOClient.swift
        CompileSwift normal x86_64 /Users/Guven/Work/clm-cordova/platforms/ios/YDNCRM/Plugins/cordova-hot-code-push-local-dev-addon/SocketIOClientSwift/SocketIOClientConfiguration.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Guven/Work/clm-cordova/platforms/ios/cordova/build-debug.xcconfig,-workspace,YDNCRM.xcworkspace,-scheme,YDNCRM,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/Guven/Work/clm-cordova/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Guven/Work/clm-cordova/platforms/ios/build/sharedpch

I'm running the last version of the plugin, with the last version of Cordova, and XCODE is 8.3.1

Best regards

**Comment by initMrD** [comment]
Same problem：
Open plugins/cordova-hot-code-push-local-dev-addon/src/ios/SocketIOClientSwift/SocketIOClientConfiguration.swift
```
public typealias Generator = Array<SocketIOClientOption>.Iterator
```
replace
```
public typealias Generator = Array<SocketIOClientOption>.Generator
```
command line run:
```
ionic platform rm ios
```
```
ionic platform add ios
```
fix it

**Comment by elewin** [comment]
I had the same problem and this fix worked for me! Thanks a million
