### ISSUE TITLE
Error: Cannot find module '../plugman/platforms/ios'

### ISSUE THREAD

**Issue by kgroat** [nordnet/cordova-hot-code-push-local-dev-addon#22]
This issue seemed to arise in `cordova-hot-code-push-plugin` (see https://github.com/nordnet/cordova-hot-code-push/issues/295), and was fixed.  The issue still seems to persist in this repo, though.

This is the output at the end of doing a `cordova -d platform add ios` while `cordova-hot-code-push-local-dev-addon` is installed:

```
Executing script found in plugin cordova-hot-code-push-local-dev-addon for hook "after_prepare": plugins/cordova-hot-code-push-local-dev-addon/scripts/ios_swiftActivationHook.js
Swift support activation hook:
Resolving module name for cordova-lib/src/cordova/util => ../cordova/util
Resolving module name for cordova-common/src/ConfigParser/ConfigParser => cordova-common/src/ConfigParser/ConfigParser
Resolving module name for cordova-lib/src/plugman/platforms => ../plugman/platforms
Resolving module name for cordova-lib/src/plugman/platforms/ios => ../plugman/platforms/ios
Error: Cannot find module '../plugman/platforms/ios'
```

**Comment by kgroat** [comment]
I believe a similar issue in `cordova-hot-code-push-local-dev-addon` is also causing this issue: https://github.com/nordnet/cordova-hot-code-push/issues/305

**Comment by beevelop** [comment]
Same reproducible problem over here.
```
Cordova Version: 7.0.1
cordova-hot-code-push-local-dev-addon: 0.4.2
cordova-hot-code-push-plugin": 1.5.3
cordova-hot-code-push-cli: 1.1.1
```

**Comment by kgroat** [comment]
@nikDemyankov is this repo not being supported anymore?

**Comment by hirbod** [comment]
@kgroat looks like another dead project :/

**Comment by Aarbel** [comment]
@kgroat @nikDemyankov @beevelop @Hirbod Have you found a way to fix it ? Thanks a lot :)
