### ISSUE TITLE
HCPLDPlugin.m Unknown type name 'SocketIOClient'

### ISSUE THREAD

**Issue by albinekb** [nordnet/cordova-hot-code-push-local-dev-addon#3]
Hi, i updated this plugin and now i can't compile it with Xcode.

![image](https://cloud.githubusercontent.com/assets/5027156/11183790/05742452-8c74-11e5-94fe-a3d7f8a06b27.png)

**Comment by nikDemyankov** [comment]
Hi, can you open `HCPLDPlugin.h` and check if `#import <YOUR_PROJECT_NAME>-Swift.h` header is included in there? If not - try to run `cordova prepare ios` (or `ionic prepare ios`) and check if it's added in there.

And by "updated this plugin" you mean moving from v1.0 of hot code push plugin to v1.1 and installing local-dev add-on? And how did you migrated: reinstalled the platform, or manually?

**Comment by nikDemyankov** [comment]
It is seems similar to issue https://github.com/nordnet/cordova-hot-code-push/issues/37 , which was fixed automatically after running `cordova prepare ios`.

**Comment by albinekb** [comment]
Header was now included,
Running `cordova prepare ios` did the magic,

Updated both plugins by first removing them and then adding them.

**Comment by nikDemyankov** [comment]
Good. Will still try to reproduce it like so, just in case.

**Comment by pengzhiqiang110** [comment]
Can you speak Chinese   I don't quite understand what you said
