### ISSUE TITLE
Won't Connect To Local Server?

### ISSUE THREAD

**Issue by johnmiroki** [nordnet/cordova-hot-code-push-local-dev-addon#5]
I am trying to follow the instruction on the QuickStart but always fail.
I noticed the ngrok.com is not accessible and suspected it was the cause of failure. Instead, I tried to instruct the app to connect to the local server created by cordova-hcp server, by adding:

``` xml
  <chcp>
    <config-file url="http://192.168.108.98:31284/chcp.json" />
    <local-development enabled="true" />
  </chcp>
```

to the project's config.xml.
still no luck. then I noticed when executing ionic run, there's the following log:

```
D:\playground\TestHCP>ionic run
Running command: "C:\Program Files\nodejs\node.exe" D:\playground\TestHCP\hooks\after_prepare\010_add_platform_class.js D:\playground\TestHCP
add to body class: platform-android
CHCP Local Development Add-on:
    Setting config-file to local server: https://4961a61c.ngrok.com/chcp.json
    Android version code is set to 21
CHCP plugin after prepare hook:
    config-file set to http://192.168.108.98:31284/chcp.json
```

I am confused by the "Setting config-file to local server: https://4961a61c.ngrok.com/chcp.json" part. Moreover, I checked the config.xml under platforms\android\res\xml and found the chcp block is different than its counterpart in the root directory of the project:

``` xml
  <chcp>
    <config-file url="https://4961a61c.ngrok.com/chcp.json"/>
    <local-development enabled="true"/>
  </chcp>
```

(the above is the one in platforms\android\res\xml ) it seems my configuration in the config.xml was overridden.

I am hoping someone may point out what's going on and what I may have been doing wrong. Thanks in advance!

**Comment by nikDemyankov** [comment]
Hi,

> Setting config-file to local server: https://4961a61c.ngrok.com/chcp.json

When you execute `cordova-hcp server` CLI client creates `.chcpenv` file in the root of your Cordova/Ionic project. In your case:

``` json
{
  "content_url": "https://4961a61c.ngrok.com",
  "config_url": "https://4961a61c.ngrok.com/chcp.json"
}
```

When project is build - `after_prepare` hook from the plugin get's executed. He reads this file, takes `config_url` and puts it in the platform specific `config.xml`. Why he does that? Well, so you would not have to do that.

> I noticed the ngrok.com is not accessible and suspected it was the cause of failure.

Yes, if you can't open `https://4961a61c.ngrok.com/chcp.json` - then ngrok is not reachable or not running. If you change hostname to the ip address, then you need:
1. Check, that it is accessible via browser: `http://192.168.108.98:31284/chcp.json`.
2. Either change in `.chcpenv` hostname `4961a61c.ngrok.com` to `192.168.108.98:31284`. Or in `plugins/cordova-hot-code-push-local-dev-addon/scripts/afterPrepareHook.js` on line [138](https://github.com/nordnet/cordova-hot-code-push-local-dev-addon/blob/master/scripts/afterPrepareHook.js#L138) change 
   
   ```
   var localServerURL = getLocalServerURLFromEnvironmentConfig(ctx);
   ```
   
   to
   
   ```
   var localServerURL = 'http://192.168.108.98:31284';
   ```

**Comment by johnmiroki** [comment]
Hi Nic. Thanks so much for your prompt reply. I'm glad you mentioned .chcpenv file. I had tried to modified it but every time I ran cordova-hcp server, the file would be set to its default ie https://4961a61c.ngrok.com . now I am going to modify afterPrepareHook.js instead and let you know how it goes.

**Comment by johnmiroki** [comment]
I modified afterPrepareHook.js file according to your instruction

``` javascript
var localServerURL = 'http://192.168.108.98:31284/chcp.json';
```

and now the cordova-hcp server can report "a user connected". however, on the app side, there's no update or reload action after I modified index.html. 
Going to learn and investigate. Any further suggestion? Thanks again!

**Comment by johnmiroki** [comment]
Tried both on emulator and actual mobile phone, both failed. The cordova-hcp server reports:

```
a user connected
File changed:  D:\playground\TestHCP\www\index.html
Config { name: 'test',
  ios_identifier: '',
  android_identifier: '',
  update: 'now',
  content_url: 'http://192.168.108.98:31284',
  release: '2016.01.08-17.31.45' }
Build 2016.01.08-17.31.45 created in D:\playground\TestHCP\www
Should trigger reload for build: 2016.01.08-17.31.45
```

so I guess the problem is on the app side? any suggestions? Thanks!

**Comment by nikDemyankov** [comment]
If you see in console `a user connected` - then emulator/device did connect to the server via sockets and listening for the updates. So most likely, it can't download new content.

Open `platforms/ios/YOUR_PROJECT_NAME.xcodeproj` in Xcode and launch the app to see the logs in Xcode console.

Also, on your emulator launch Safari and open `http://192.168.108.98:31284/chcp.json`. If it's not opening, then use `http://localhost:31284/chcp.json` instead. If localhost is opening - use it instead of the ip address.

Also, after opening chcp.json in Safari - check, that `content_url` property is set correctly. For example:

``` json
{
  "autogenerated": true,
  "release": "2016.01.08-11.00.04",
  "content_url": "http://localhost:31284",
  "update": "now"
}
```

**Comment by johnmiroki** [comment]
Hi Nik, I finally figure out what was wrong. There's nothing wrong with the plugin per se. The plugin would phone home and get chcp.json successfully. But it wouldn't be able to subsequently ask for the manifest with success, cuz I realized I'd have to set up a dev version of cordova-hcp.json for cordova-hcp cli, so that it will generate proper chcp.json (to be exact, content-url pointing to local server)  for development purposes. It's a bit inconvenient, I kinda hope the local-dev-plugin can kick in and modify the cordova-hcp.json for me. But anyway, good work! Thanks!!! I'm going to explore more on the hot code push plugin itself. See you there?

**Comment by nikDemyankov** [comment]
Hi,

Glad to hear, that you find the problem :) It's strange, that you had to do that. Will look into this.

> I'm going to explore more on the hot code push plugin itself. See you there?

Sure, if you find a bug or hit some problem - just post a question in there.

**Comment by johnmiroki** [comment]
I'm a novice so don't bother look into the so-called problem just yet. Maybe there isn't anything wrong after all, just me being silly lol. Now I've adjusted my workflow a little: put aside the local dev addon, and only use cordova-hcp build to generate manifest after I change something in the www folder, then I start up my own http server:

``` python
python -m SimpleHTTPServer 8081
```

This way I'll be able to focus on testing and developing around the hot code push plugin. Of course it also means I'll have to modify config.xml(<config-file>) and cordova-hcp.json(content_url) before deploying to production environment. (just keeping a record here for novices whoever  may face similar problems to mine)

**Comment by nikDemyankov** [comment]
Good, thanks for the info :)
