### ISSUE TITLE
New native-interface setting is discarded when using this plugin

### ISSUE THREAD

**Issue by alexbuijs** [nordnet/cordova-hot-code-push-local-dev-addon#7]
When using this plugin, the native-interface setting in config.xml is discarded at build time (only the config-file and local-development settings of the chcp tag are retained), causing the cordova-hot-code-push-plugin to use the default setting of 1. When the chcp.json specifies a higher number than 1 for min_native_interface, every reload trigger causes the plugin to error with "Application build version is too low for this update", instead of a hot reload.

**Comment by nikDemyankov** [comment]
Thanks, will fix that.

**Comment by nikDemyankov** [comment]
Released v0.2.1 with the fix. Should work now. If not - please, reopen the issue.

**Comment by alexbuijs** [comment]
Thanks! 👍
