### ISSUE TITLE
Disable ngrok?

### ISSUE THREAD

**Issue by elewin** [nordnet/cordova-hot-code-push-local-dev-addon#8]
Is it possible to disable the ngrok functionality and just have the live server push go through the local server only?

**Comment by nikDemyankov** [comment]
Currently this add-on depends on plugin's CLI client. When you run `cordova-hcp server` - CLI client create's `.chcpenv` file with server preferences (actually, just it's url). When you run `cordova prepare` - add-on reads `.chcpenv` and set's `<config-file url="" />` in platform specific `config.xml`. When application is launched - add-on connects with socket.io library to this server and listen for update events. When captured - it executes `chcp.fetchUpdate()` on JS side.

If you want to use your own server for development - you need two things:
1. Your update server should support socket connections, and application should be able to connect to it with socket.io library.
2. Create `.chcpenv` file and set in it correct server address. Or [modify add-on hook](https://github.com/nordnet/cordova-hot-code-push-local-dev-addon/blob/master/scripts/afterPrepareHook.js#L14) to read preferences from other file.
